### ISSUE TITLE
Don't use :warning: for everything being up-to-date

### ISSUE THREAD

**Issue by docwhat** [crazy-max/ghaction-github-labeler#112]
When the labels match the configuration file, the message generated is:

```
⚠️ Skipping rename 'dependencies' label to ':game_die: dependencies'. Already exists
```

Using ⚠️ make it look like something needs to be looked at by the use.

Instead, use ✅ or something else to show that things are in their desired state.

The verbiage should probably be changed to be more positive.

Suggestion:

```
✅ Nothing to do for `:game_die: dependencies`.
```

or

```
✅ `:game_die: dependencies` is up-to-date.
```

**Comment by crazy-max** [comment]
@docwhat Done, thanks!
