### ISSUE TITLE
Idea: Can you suggest a way to initiate labels.yml file

### ISSUE THREAD

**Issue by oncleben31** [crazy-max/ghaction-github-labeler#117]
It could be interesting you suggest in the documentation a way to initiate the `labels.yml`file with:

- file already construct using best practices from the developers community
- a way to construct the file from already existing labels (from our own repositories or inspired from others)

**Comment by oncleben31** [comment]
Too bad because it could be useful.

**Comment by crazy-max** [comment]
@oncleben31 

> file already construct using best practices from the developers community

That's not the purpose of this repo but you can find some of them with this GitHub search query: https://github.com/search?q=name+path%3A%2F.github+filename%3Alabels.yml&type=Code&ref=advsearch&l=&l=

> a way to construct the file from already existing labels (from our own repositories or inspired from others)

I think that should be done through a CLI and not a GitHub Action itself. Maybe use [this one](https://github.com/tonglil/labeler#scanning-labels).
