### ISSUE TITLE
Allow hash in color codes

### ISSUE THREAD

**Issue by armsnyder** [crazy-max/ghaction-github-labeler#153]
It would be awesome to allow configuring colors in `#112233` format, because it plays nicer with [IDE plugins](https://github.com/enyancc/vscode-ext-color-highlight) and makes previewing colors easier.
<img width="444" alt="Screen Shot 2022-01-31 at 4 44 58 PM" src="https://user-images.githubusercontent.com/9969202/151896381-a1cb3b91-2ed6-47b5-9a06-0f1044575820.png">

**Comment by davorpa** [comment]
Any planning for this?
