### ISSUE TITLE
##[error]Cannot find YAML file .github/labels.yml

### ISSUE THREAD

**Issue by knor-el-snor** [crazy-max/ghaction-github-labeler#81]
I've tried custom paths, built-in on but I always receive the following error

```
##[error]Cannot find YAML file .github/labels.yml
```

The file is there and contains the following:
```
- name: "Core"
  color: "d73a4a"
  description: "Core API Team"
```

Any idea what could be wrong?

**Comment by crazy-max** [comment]
@knor-el-snor Do you have a link to your workflow yml?
